# https://taskfile.dev

version: "3"

silent: true

vars:
  DOCKER_USER: '{{env "DOCKER_USER"}}'
  COMMIT:
    sh: git rev-parse --short HEAD
  IMAGE_TAG: "{{.COMMIT}}"
  PROMO_TAG: latest
  REGISTRY: '{{.REGISTRY | default (env "REGISTRY") | default "docker.io" }}'
  IMAGE: "{{.DOCKER_USER}}/clible"

tasks:
  default:
    cmds:
      - task: show-image
  show-image:
    desc: Print fully-qualified image references
    cmds:
      - echo "{{.REGISTRY}}/{{.IMAGE}}:{{.IMAGE_TAG}}"
      - echo "{{.REGISTRY}}/{{.IMAGE}}:{{.PROMO_TAG}}"

  build:
    desc: "Build Docker image"
    deps: []
    cmds:
      - docker build -t {{.REGISTRY}}/{{.IMAGE}}:{{.IMAGE_TAG}} .

  tag:
    desc: Re-tag existing image to latest tag
    deps: [build]
    cmds:
      - docker tag {{.REGISTRY}}/{{.IMAGE}}:{{.IMAGE_TAG}} {{.REGISTRY}}/{{.IMAGE}}:{{.PROMO_TAG}}
      - echo "Tagged {{.REGISTRY}}/{{.IMAGE}}:{{.IMAGE_TAG}} -> {{PROMO_TAG}}"

  push:
    desc: Push both image tag and latest tag
    deps: [tag]
    cmds:
      - docker push {{.REGISTRY}}/{{.IMAGE}}:{{.IMAGE_TAG}}
      - docker push {{.REGISTRY}}/{{.IMAGE}}:{{.PROMO_TAG}}
